### ISSUE TITLE
Issue with problems like "1002A1" or any other problem having sub-parts

### ISSUE THREAD

**Issue by AkshatAggarwal14** [lkiThakur/cfshare#1]
# The issue
If we import the problem [1002A1](www.codeforces.com/contest/1002/problem/A1), the link generated was www.codeforces.com/contest/1002A/problem/1 instead of www.codeforces.com/contest/1002/problem/A1

**Comment by adarsh-sgh** [comment]
Thanks for the detailed info @AkshatAggarwal14 .
your detailed analysis helped us to fix the issue faster  : )
closing this now .
